<html>
<head>
<title>
CppUnit - The Unit Testing Library
</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
<link href="tabs.css" rel="stylesheet" type="text/css">
</head>

<body bgcolor="#ffffff"> 
<table width="100%">
  <tr>
    <td width="40%" align="left" valign="center">
      <a href="http://sourceforge.net/projects/cppunit">
      CppUnit project page
      </a>
    </td>
    <td>
      <a href="FAQ">FAQ</a>
    </td>
    <td width="40%" align="right" valign="center">
      <a href="http://cppunit.sourceforge.net">CppUnit home page</a>
    </td>
  </tr>
</table>

<hr>
<!-- Generated by Doxygen 1.4.7 -->
<div class="tabs">
  <ul>
    <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
    <li><a href="modules.html"><span>Modules</span></a></li>
    <li><a href="namespaces.html"><span>Namespaces</span></a></li>
    <li id="current"><a href="classes.html"><span>Classes</span></a></li>
    <li><a href="files.html"><span>Files</span></a></li>
    <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="classes.html"><span>Alphabetical&nbsp;List</span></a></li>
    <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>TestFailure Class Reference<br>
<small>
[<a class="el" href="group___browsing_collected_test_result.html">Browsing collected test result</a>]</small>
</h1><!-- doxytag: class="TestFailure" -->Record of a failed <a class="el" href="class_test.html">Test</a> execution.<p>
A <a class="el" href="class_test_failure.html">TestFailure</a> collects a failed test together with the caught exception.  
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="_test_failure_8h-source.html">TestFailure.h</a>&gt;</code>
<p>
Collaboration diagram for TestFailure:<p><center><img src="class_test_failure__coll__graph.png" border="0" usemap="#_test_failure__coll__map" alt="Collaboration graph"></center>
<map name="_test_failure__coll__map">
<area href="class_test.html" shape="rect" coords="5,101,51,131" alt="">
<area href="class_exception.html" shape="rect" coords="96,101,181,131" alt="">
<area href="class_source_line.html" shape="rect" coords="31,5,124,35" alt="">
<area href="class_message.html" shape="rect" coords="160,5,237,35" alt="">
</map>
<center><font size="2">[<a href="graph_legend.html">legend</a>]</font></center><a href="class_test_failure-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#0c1b4cee94278814ab7a4ba72f94dac3">TestFailure</a> (<a class="el" href="class_test.html">Test</a> *failedTest, <a class="el" href="class_exception.html">Exception</a> *thrownException, bool isError)</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Constructs a <a class="el" href="class_test_failure.html">TestFailure</a> with the given test and exception.  <a href="#0c1b4cee94278814ab7a4ba72f94dac3"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#117d2f3616bed325e97b0ac2fe7d9e4b">~TestFailure</a> ()</td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Deletes the owned exception.  <a href="#117d2f3616bed325e97b0ac2fe7d9e4b"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual <a class="el" href="class_test.html">Test</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#8c7da6077f68897785a69cea6c2b7825">failedTest</a> () const </td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the failed test.  <a href="#8c7da6077f68897785a69cea6c2b7825"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual <a class="el" href="class_exception.html">Exception</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#c12b8f4d9a6a1f130834cf08287d869d">thrownException</a> () const </td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the thrown exception. Never <code>NULL</code>.  <a href="#c12b8f4d9a6a1f130834cf08287d869d"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual <a class="el" href="class_source_line.html">SourceLine</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#0da7fc89d01c8b42c96cd0542eba58eb">sourceLine</a> () const </td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the failure location.  <a href="#0da7fc89d01c8b42c96cd0542eba58eb"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#0b6c1ee50d2186a4918f015d7879e8dd">isError</a> () const </td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates if the failure is a failed assertion or an error.  <a href="#0b6c1ee50d2186a4918f015d7879e8dd"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual std::string&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#f2f5978f08aa97106acdb09a57807a0e">failedTestName</a> () const </td></tr>

<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the name of the failed test.  <a href="#f2f5978f08aa97106acdb09a57807a0e"></a><br></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual <a class="el" href="class_test_failure.html">TestFailure</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#eba45f44e148dc01146c615da438ab91">clone</a> () const </td></tr>

<tr><td colspan="2"><br><h2>Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="class_test.html">Test</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#2ba79089909967b45aedc4992b51553a">m_failedTest</a></td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="class_exception.html">Exception</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#96bfae3c1f32d0c1729501d68016f431">m_thrownException</a></td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#bf258e5bec289b51fb13147a62b8b75d">m_isError</a></td></tr>

<tr><td colspan="2"><br><h2>Private Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#eef404204f8114c31bb5d3049b22acab">TestFailure</a> (const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;other)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="class_test_failure.html">TestFailure</a> &amp;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a9eef2b8d4177f6b59e818810dc28b66">operator=</a> (const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;other)</td></tr>

</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
Record of a failed <a class="el" href="class_test.html">Test</a> execution.<p>
A <a class="el" href="class_test_failure.html">TestFailure</a> collects a failed test together with the caught exception. 
<p>
<a class="el" href="class_test_failure.html">TestFailure</a> assumes lifetime control for any exception passed to it. 
<p>
<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" name="0c1b4cee94278814ab7a4ba72f94dac3"></a><!-- doxytag: member="TestFailure::TestFailure" ref="0c1b4cee94278814ab7a4ba72f94dac3" args="(Test *failedTest, Exception *thrownException, bool isError)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">CPPUNIT_NS_BEGIN TestFailure::TestFailure           </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_test.html">Test</a> *&nbsp;</td>
          <td class="paramname"> <em>failedTest</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_exception.html">Exception</a> *&nbsp;</td>
          <td class="paramname"> <em>thrownException</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&nbsp;</td>
          <td class="paramname"> <em>isError</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Constructs a <a class="el" href="class_test_failure.html">TestFailure</a> with the given test and exception. 
<p>

</div>
</div><p>
<a class="anchor" name="117d2f3616bed325e97b0ac2fe7d9e4b"></a><!-- doxytag: member="TestFailure::~TestFailure" ref="117d2f3616bed325e97b0ac2fe7d9e4b" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TestFailure::~TestFailure           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Deletes the owned exception. 
<p>

</div>
</div><p>
<a class="anchor" name="eef404204f8114c31bb5d3049b22acab"></a><!-- doxytag: member="TestFailure::TestFailure" ref="eef404204f8114c31bb5d3049b22acab" args="(const TestFailure &amp;other)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TestFailure::TestFailure           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;&nbsp;</td>
          <td class="paramname"> <em>other</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [private]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="eba45f44e148dc01146c615da438ab91"></a><!-- doxytag: member="TestFailure::clone" ref="eba45f44e148dc01146c615da438ab91" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test_failure.html">TestFailure</a> * TestFailure::clone           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<a class="anchor" name="8c7da6077f68897785a69cea6c2b7825"></a><!-- doxytag: member="TestFailure::failedTest" ref="8c7da6077f68897785a69cea6c2b7825" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test.html">Test</a> * TestFailure::failedTest           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Gets the failed test. 
<p>

</div>
</div><p>
<a class="anchor" name="f2f5978f08aa97106acdb09a57807a0e"></a><!-- doxytag: member="TestFailure::failedTestName" ref="f2f5978f08aa97106acdb09a57807a0e" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string TestFailure::failedTestName           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Gets the name of the failed test. 
<p>

</div>
</div><p>
<a class="anchor" name="0b6c1ee50d2186a4918f015d7879e8dd"></a><!-- doxytag: member="TestFailure::isError" ref="0b6c1ee50d2186a4918f015d7879e8dd" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool TestFailure::isError           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Indicates if the failure is a failed assertion or an error. 
<p>

</div>
</div><p>
<a class="anchor" name="a9eef2b8d4177f6b59e818810dc28b66"></a><!-- doxytag: member="TestFailure::operator=" ref="a9eef2b8d4177f6b59e818810dc28b66" args="(const TestFailure &amp;other)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test_failure.html">TestFailure</a>&amp; TestFailure::operator=           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;&nbsp;</td>
          <td class="paramname"> <em>other</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [private]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<a class="anchor" name="0da7fc89d01c8b42c96cd0542eba58eb"></a><!-- doxytag: member="TestFailure::sourceLine" ref="0da7fc89d01c8b42c96cd0542eba58eb" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_source_line.html">SourceLine</a> TestFailure::sourceLine           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Gets the failure location. 
<p>

</div>
</div><p>
<a class="anchor" name="c12b8f4d9a6a1f130834cf08287d869d"></a><!-- doxytag: member="TestFailure::thrownException" ref="c12b8f4d9a6a1f130834cf08287d869d" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_exception.html">Exception</a> * TestFailure::thrownException           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Gets the thrown exception. Never <code>NULL</code>. 
<p>

</div>
</div><p>
<hr><h2>Member Data Documentation</h2>
<a class="anchor" name="2ba79089909967b45aedc4992b51553a"></a><!-- doxytag: member="TestFailure::m_failedTest" ref="2ba79089909967b45aedc4992b51553a" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test.html">Test</a>* <a class="el" href="class_test_failure.html#2ba79089909967b45aedc4992b51553a">TestFailure::m_failedTest</a><code> [protected]</code>          </td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<a class="anchor" name="bf258e5bec289b51fb13147a62b8b75d"></a><!-- doxytag: member="TestFailure::m_isError" ref="bf258e5bec289b51fb13147a62b8b75d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_test_failure.html#bf258e5bec289b51fb13147a62b8b75d">TestFailure::m_isError</a><code> [protected]</code>          </td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<a class="anchor" name="96bfae3c1f32d0c1729501d68016f431"></a><!-- doxytag: member="TestFailure::m_thrownException" ref="96bfae3c1f32d0c1729501d68016f431" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_exception.html">Exception</a>* <a class="el" href="class_test_failure.html#96bfae3c1f32d0c1729501d68016f431">TestFailure::m_thrownException</a><code> [protected]</code>          </td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>

</div>
</div><p>
<hr>The documentation for this class was generated from the following files:<ul>
<li><a class="el" href="_test_failure_8h-source.html">TestFailure.h</a><li><a class="el" href="_test_failure_8cpp.html">TestFailure.cpp</a></ul>
<hr>
<table width="100%">
  <tr>
    <td width="10%" align="left" valign="center">
      <a href="http://sourceforge.net"> 
      <img
      src="http://sourceforge.net/sflogo.php?group_id=11795"
      width="88" height="31" border="0" alt="SourceForge Logo"></a>
    </td>
    <td width="20%" align="left" valign="center">
      hosts this site.
    </td>
    <td>
    </td>
    <td align="right" valign="center">
      Send comments to:<br>
      <a href="mailto:cppunit-devel@lists.sourceforge.net">CppUnit Developers</a>
    </td>
  </tr>
</table>

</body> 
</html>
